{% set name = "re2" %}
{% set version = "2018-08-01" %}
{% set dotversion = version.replace('-', '.') %}
{% set sha256 = "7c995c91c12201e61738f35cf4d1362758894d674a1e71dd116cafb4d860b752" %}

package:
  name: {{ name|lower }}
  version: {{ dotversion }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  detect_binary_files_with_prefix: True
  skip: True  # [vc<14]  # [win]

requirements:
  build:
    - cmake >=3.4
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libre2.so  # [linux]
    - test -f ${PREFIX}/lib/libre2.dylib  # [osx]
    - test -f ${PREFIX}/include/re2/re2.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\re2\\re2.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\re2.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\re2.dll exit 1  # [win]

about:
  home: https://github.com/google/re2/
  license: BSD 3-clause
  license_file: LICENSE
  summary: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression
    engines like those used in PCRE, Perl, and Python. It is a C++ library.
  dev_url: https://github.com/google/re2/

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
