{% set name = "re2" %}
{% set version = "2024-02-01" %}
{% set dotversion = version.replace('-', '.') %}
{% set sha256 = "cd191a311b84fcf37310e5cd876845b4bf5aee76fdd755008eef3b6478ce07bb" %}

package:
  name: {{ name|lower }}
  version: {{ dotversion }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://github.com/google/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage("re2", max_pin="x.x.x") }}
  missing_dso_whitelist:
    - '$RPATH/ld64.so.1'

requirements:
  build:
    - cmake
    - make  # [unix]
    - ninja-base  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libabseil

test:
  commands:
    - test -f ${PREFIX}/lib/libre2.so  # [linux]
    - test -f ${PREFIX}/lib/libre2.dylib  # [osx]
    - test ! -f ${PREFIX}/lib/libre2.a  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/re2.pc  # [unix]
    - test -f ${PREFIX}/include/re2/re2.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\re2\\re2.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\re2.lib exit 1  # [win]
    - if exist %PREFIX%\\Library\\lib\\re2_static.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\re2.dll exit 1  # [win]

about:
  home: https://github.com/google/re2/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  description: |
    RE2 is a fast, safe, thread-friendly alternative to backtracking regular expression
    engines like those used in PCRE, Perl, and Python. It is a C++ library.
  dev_url: https://github.com/google/re2/
  doc_url: https://github.com/google/re2/wiki

extra:
  recipe-maintainers:
    - scopatz
    - isuruf
    - wesm
    - xhochy
    - kszucs
    - pitrou
