travis:
  secure:
    BINSTAR_TOKEN: ej610n+jYpSXSHCJZ8/52MLygMkMZ++Ti4czzCq+L3zonI5H1V6fPJlBsJpV4Nt5q2ZYkMBLZwcTz3c23B82xKIrdzpUhd+SfVrfIPBLVWLdhhs0aQvryrSwAVD84Kaf+LPZprcrNt4w2FkXJMe5g5673wbzQkwWSIkwDRZ/BMluksZu+BD0GoWDbGJCk8XUOf4Co9tu5WfJBvQTuM6DKY2GxwHRMa7uia3QCl6eaoAN1c7ParwxaWAY4k8++WRZCf104TG6WvNbPPMTAi8HGEadled66w0tbK/p9xK2JT1n3J+SZnR4ftW5TdQekNiPHKg0ThFH3aKUtAp6uFywr3AzPX6blj+gru8ypvDh3iOu39qzofvvDRctNO5v1okrpx7/lnrP13fYMsogb+nEIFlKxj4lucDziZl+3RekRTI59YqJpo71FZMommXHZTtZA8bBLcL+rBVHMV2pzYFIEyxEAd2SDJh2JOEPAnLZFs8YmZN3xzI4E1yAO6DyCxtEUETPxjSZYrIMuUolKyr3/MYVHQ89FkAWXNDnFVbvybUMPHJXxDVRLalHU5sSCefGgfhJTHyhGgrZG8AJyMpxVpYxRHDcaNk77zmHvyywH7a5cZVOL8TdNvQ7t49LGpwZ9Wm3cnA4j2BgQuFFGfYWv/xOfbjKSNANsTaa97k5DFA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
